preferred-supported-locales: [en, id]
synthetic-package: false
output-dir: lib/l10n/generated
arb-dir: lib/l10n
template-arb-file: intl_en.arb
output-localization-file: tchain_payment_localizations.dart
output-class: TChainPaymentLocalizations