name: t_chain_payment_sdk
description: T-Chain Payment is a B2B service helping SMEs add another channel to convert in-app point/money into crypto currency and vice versa using blockchain technology with minimum efforts
version: 0.0.2
homepage: https://www.tokoin.io/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.5
  flutter_svg: ^0.23.0+1
  uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  url_launcher_platform_interface: ^2.1.0
  plugin_platform_interface: ^2.1.2

# ref: https://stackoverflow.com/a/37484053/1654338
false_secrets:
  - /example/android/app/google-services.json
  - /example/ios/Runner/GoogleService-Info.plist
  - /example/lib/firebase_options.dart


# The following section is specific to Flutter.
# flutter:
#   assets:
#     - assets/